# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\elizavet\Documents\PSoC Creator\Microcontrollers_part_2\lab-1.cydsn\lab-1.cyprj
# Date: Wed, 02 Nov 2022 09:46:32 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\elizavet\Documents\PSoC Creator\Microcontrollers_part_2\lab-1.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\elizavet\Documents\PSoC Creator\Microcontrollers_part_2\lab-1.cydsn\lab-1.cyprj
# Date: Wed, 02 Nov 2022 09:46:28 GMT
